---
# Bridge
## Deposits
- anonymous: 0
  inputs:
    - indexed: 1
      internalType: address
      name: sender
      type: address
    - indexed: 1
      internalType: contract IERC20
      name: token
      type: address
    - indexed: 0
      internalType: uint256
      name: amount
      type: uint256
    - indexed: 0
      internalType: bytes32
      name: accountID
      type: bytes32
  name: DepositedERC20
  type: event

- anonymous: 0
  inputs:
    - indexed: 1
      internalType: address
      name: sender
      type: address
    - indexed: 0
      internalType: bytes32
      name: accountID
      type: bytes32
    - indexed: 0
      internalType: bool
      name: isContract
      type: bool
  name: LinkAccountID
  type: event

## Withdrawals
- anonymous: 0
  inputs:
    - indexed: 1
      internalType: bytes32
      name: hash
      type: bytes32
  name: PendingWithdraw
  type: event
- anonymous: 0
  inputs:
    - indexed: 1
      internalType: bytes32
      name: hash
      type: bytes32
  name: UnpendingWithdraw
  type: event
- anonymous: 0
  inputs:
    - indexed: 1
      internalType: bytes32
      name: hash
      type: bytes32
  name: WithdrawRequestHash
  type: event
- anonymous: 0
  inputs:
    - indexed: 1
      internalType: bytes32
      name: hash
      type: bytes32
  name: WithdrawalHash
  type: event
- anonymous: 0
  inputs:
    - indexed: 1
      internalType: bytes32
      name: hash
      type: bytes32
  name: WithdrawalToPostchain
  type: event

# Staking
- anonymous: 0
  name: StakeUpdate
  type: event
  inputs:
    - indexed: 1
      internalType: address
      name: from
      type: address
    - indexed: 0
      internalType:
      name: balance
      type: uint64
- anonymous: 0
  name: WithdrawRequest
  type: event
  inputs:
    - indexed: 1
      internalType: address
      name: from
      type: address
    - indexed: 0
      internalType:
      name: until
      type: uint64
