lib.ft4.core.accounts.strategies.transfer:
  rules:
    - sender_blockchain: "*"
      sender: "*"
      recipient: "*"
      asset:
        - id: x"5F16D1545A0881F971B164F1601CBBF51C29EFD0633B2730DA18C403C3B428B5"
          min_amount: 10000000L
      timeout_days: 3
      strategy:
      - "fee"
    - sender_blockchain: "*"
      sender: "*"
      recipient: "*"
      asset:
        - name: ChoccyUSD # from this chain
          min_amount: 1000000000000000000L
      timeout_days: 3
      strategy:
      - "fee"
lib.ft4.core.accounts.strategies.transfer.fee:
  asset:
    - id: x"5F16D1545A0881F971B164F1601CBBF51C29EFD0633B2730DA18C403C3B428B5"
      amount: 10000000L
    - name: ChoccyUSD # from this chain
      amount: 1000000000000000000L
  fee_account: x"0000000000000000000000000000000000000000000000000000000000000000"